### ISSUE TITLE
libfzy darwin arm64

### ISSUE THREAD

**Issue by mherna** [romgrk/fzy-lua-native#9]
Hi I am trying to run the benchmark, on a mac mini running the m1 chip, I get the following error:
```
luajit: ./lua/native.lua:34: dlopen(./lua/../static/libfzy-darwin-arm64.so, 5): image not found
stack traceback:
	[C]: in function 'load'
	./lua/native.lua:34: in main chunk
	[C]: in function 'require'
	benchmark.lua:9: in main chunk
	[C]: at 0x01028e2a0c
```
I believe a ```libfzy-darwin-arm64.so``` file is missing in the ```static``` folder

**Comment by romgrk** [comment]
Not available yet on GHA if I'm not mistaken :/ https://github.com/actions/runner/issues/805

**Comment by mherna** [comment]
@romgrk yeah, that's why I closed the issue :/ ... the good thing is that it does compile correctly! And after building it, it worked as expected.
